export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_ALL_CUSTOMERS_REQUEST = "GET_ALL_CUSTOMERS_REQUEST";
export const GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS";
export const GET_ALL_CUSTOMERS_FAILURE = "GET_ALL_CUSTOMERS_FAILURE";
export const SET_COGNITO_USER = "SET_COGNITO_USER";
export const COGNITO_LOGIN_REQUEST = "COGNITO_LOGIN_REQUEST";
export const COGNITO_LOGIN_SUCCESS = "COGNITO_LOGIN_SUCCESS";
export const COGNITO_LOGIN_FAILURE = "COGNITO_LOGIN_FAILURE";
export const COGNITO_LOGOUT = "COGNITO_LOGOUT";
export const LOGOUT="LOGOUT";